// frontend/src/lib/leagues-data.ts
// Dataset statique des championnats et équipes disponibles.
// Les noms correspondent exactement aux clés du KNOWN_ELO backend
// pour garantir que les prédictions utilisent les bons ELO.

export interface LeagueData {
  name: string;
  country: string;
  teams: string[];
}

export const LEAGUES_DATA: LeagueData[] = [
  {
    name: "Premier League",
    country: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Angleterre",
    teams: [
      "Manchester City",
      "Arsenal",
      "Liverpool",
      "Chelsea",
      "Manchester United",
      "Tottenham",
      "Newcastle",
      "Aston Villa",
      "Brighton",
      "West Ham",
      "Crystal Palace",
      "Brentford",
      "Fulham",
      "Wolves",
      "Everton",
      "Nottingham Forest",
      "Bournemouth",
      "Luton Town",
      "Sheffield United",
      "Burnley",
    ],
  },
  {
    name: "La Liga",
    country: "🇪🇸 Espagne",
    teams: [
      "Real Madrid",
      "Barcelona",
      "Atletico Madrid",
      "Sevilla",
      "Real Sociedad",
      "Villarreal",
      "Athletic Bilbao",
      "Real Betis",
      "Valencia",
      "Osasuna",
      "Celta Vigo",
      "Getafe",
      "Girona",
      "Mallorca",
      "Las Palmas",
      "Alaves",
      "Rayo Vallecano",
      "Cadiz",
      "Almeria",
      "Granada",
    ],
  },
  {
    name: "Bundesliga",
    country: "🇩🇪 Allemagne",
    teams: [
      "Bayern Munich",
      "Dortmund",
      "Leverkusen",
      "RB Leipzig",
      "Union Berlin",
      "Freiburg",
      "Eintracht Frankfurt",
      "Hoffenheim",
      "Werder Bremen",
      "Wolfsburg",
      "Mainz",
      "Augsburg",
      "Borussia Monchengladbach",
      "Stuttgart",
      "Bochum",
      "Cologne",
      "Heidenheim",
      "Darmstadt",
    ],
  },
  {
    name: "Ligue 1",
    country: "🇫🇷 France",
    teams: [
      "PSG",
      "Marseille",
      "Monaco",
      "Lyon",
      "Lens",
      "Nice",
      "Rennes",
      "Lille",
      "Toulouse",
      "Montpellier",
      "Reims",
      "Nantes",
      "Strasbourg",
      "Lorient",
      "Metz",
      "Brest",
      "Le Havre",
      "Clermont",
    ],
  },
  {
    name: "Serie A",
    country: "🇮🇹 Italie",
    teams: [
      "Inter Milan",
      "AC Milan",
      "Napoli",
      "Juventus",
      "Roma",
      "Lazio",
      "Atalanta",
      "Fiorentina",
      "Bologna",
      "Torino",
      "Monza",
      "Sassuolo",
      "Udinese",
      "Genoa",
      "Lecce",
      "Cagliari",
      "Frosinone",
      "Salernitana",
      "Verona",
      "Empoli",
    ],
  },
  {
    name: "Équipes Nationales",
    country: "🌍 International",
    teams: [
      "France",
      "Argentine",
      "Angleterre",
      "Espagne",
      "Brésil",
      "Allemagne",
      "Portugal",
      "Italie",
      "Pays-Bas",
      "Belgique",
      "Croatie",
      "Maroc",
      "Uruguay",
      "Mexique",
      "Sénégal",
    ],
  },
];
